In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/heart-disease-dataset/documentation.pdf
/kaggle/input/heart-disease-dataset/heart_statlog_cleveland_hungary_final.csv


In [5]:
df = pd.read_csv('/kaggle/input/heart-disease-dataset/heart_statlog_cleveland_hungary_final.csv')

In [7]:
df.head(1)

age  sex  chest pain type  resting bp s  cholesterol  fasting blood sugar  \
0   40    1                2           140          289                    0   

   resting ecg  max heart rate  exercise angina  oldpeak  ST slope  target  
0            0             172                0      0.0         1       0

In [11]:
df = df.drop(['oldpeak'],axis=1)

In [13]:
df.dropna(inplace=True)

In [14]:
df

age  sex  chest pain type  resting bp s  cholesterol  \
0      40    1                2           140          289   
1      49    0                3           160          180   
2      37    1                2           130          283   
3      48    0                4           138          214   
4      54    1                3           150          195   
...   ...  ...              ...           ...          ...   
1185   45    1                1           110          264   
1186   68    1                4           144          193   
1187   57    1                4           130          131   
1188   57    0                2           130          236   
1189   38    1                3           138          175   

      fasting blood sugar  resting ecg  max heart rate  exercise angina  \
0                       0            0             172                0   
1                       0            0             156                0   
2                       0            1              98                0   
3                       0            0             108                1   
4                       0            0             122                0   
...                   ...          ...             ...              ...   
1185                    0            0             132                0   
1186                    1            0             141                0   
1187                    0            0             115                1   
1188                    0            2             174                0   
1189                    0            0             173                0   

      ST slope  target  
0            1       0  
1            2       1  
2            1       0  
3            2       1  
4            1       0  
...        ...     ...  
1185         2       1  
1186         2       1  
1187         2       1  
1188         2       1  
1189         1       0  

[1190 rows x 11 columns]

In [18]:
from sklearn.model_selection import train_test_split
X = df.iloc[:,0:10]
y = df.iloc[:,-1]

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [20]:
X_train

age  sex  chest pain type  resting bp s  cholesterol  \
364    56    1                4           120            0   
161    49    1                4           128          212   
56     31    1                4           120          270   
131    46    1                4           110          202   
600    56    1                4           130          203   
...   ...  ...              ...           ...          ...   
109    39    1                2           190          241   
418    44    1                4           130          209   
589    67    1                4           140          219   
1127   41    1                2           110          235   
974    53    0                3           128          216   

      fasting blood sugar  resting ecg  max heart rate  exercise angina  \
364                     0            1             148                0   
161                     0            0              96                1   
56                      0            0             153                1   
131                     0            0             150                1   
600                     1            0              98                0   
...                   ...          ...             ...              ...   
109                     0            0             106                0   
418                     0            1             127                0   
589                     0            1             122                1   
1127                    0            0             153                0   
974                     0            2             115                0   

      ST slope  
364          2  
161          2  
56           2  
131          2  
600          2  
...        ...  
109          1  
418          1  
589          2  
1127         1  
974          1  

[952 rows x 10 columns]

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()

In [23]:
X_train = scaler.fit_transform(X_train)

In [25]:
X_train

array([[ 0.23292114,  0.55631921,  0.83433104, ...,  0.34331707,
        -0.76939798,  0.60626884],
       [-0.51476021,  0.55631921,  0.83433104, ..., -1.67707856,
         1.29971748,  0.60626884],
       [-2.43736942,  0.55631921,  0.83433104, ...,  0.53758588,
         1.29971748,  0.60626884],
       ...,
       [ 1.40784899,  0.55631921,  0.83433104, ..., -0.66688075,
         1.29971748,  0.60626884],
       [-1.36925319,  0.55631921, -1.2894207 , ...,  0.53758588,
        -0.76939798, -1.02876781],
       [-0.08751372, -1.79752917, -0.22754483, ..., -0.93885708,
        -0.76939798, -1.02876781]])

In [26]:
X_test = scaler.transform(X_test)

In [27]:
X_test

array([[ 0.33973277,  0.55631921,  0.83433104, ..., -1.83249361,
         1.29971748,  0.60626884],
       [-0.08751372,  0.55631921, -1.2894207 , ...,  0.88726973,
        -0.76939798, -1.02876781],
       [-1.36925319,  0.55631921,  0.83433104, ..., -0.8222958 ,
         1.29971748,  0.60626884],
       ...,
       [ 0.9806025 ,  0.55631921,  0.83433104, ..., -0.70573451,
         1.29971748, -1.02876781],
       [-0.19432535,  0.55631921, -2.35129658, ...,  1.97517507,
        -0.76939798,  0.60626884],
       [ 0.12610952,  0.55631921,  0.83433104, ..., -1.52166351,
        -0.76939798,  0.60626884]])

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
clf = LogisticRegression()

In [32]:
clf.fit(X_train,y_train)

LogisticRegression()

In [33]:
y_pred = clf.predict(X_test)

In [34]:
y_pred

array([1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1])

In [37]:
y_test.values

array([1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1])

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
accuracy_score(y_test,y_pred)

0.8361344537815126